<div class="wlcSidebar">
<h2>Log in...</h2>
<form method="post" action="<?php echo $this->url(array(
    'controller' => 'account',
    'action' => 'login',
)) ?>">
<p class="right">
<label for="loginUsername" accesskey="l">Username:</label>
<input name="username" id="loginUsername" type="text" size="20" /><br />
<label for="loginPassword">Password:</label>
<input name="password" id="loginPassword" type="password" size="20" /><br />
<label for="rememberme" class="info" title="Check this to log in automatically on your next visit. Don't use it on shared computers.">Remember me:</label>
<input name="rememberme" id="rememberme" type="checkbox" value="1" />
<script type="text/javascript">
document.write('<input name="tzDiff" id="tzDiff" type="hidden" value="'
    + (new Date().getTimezoneOffset()*-60)
    + '" />');
</script>
</p>
<p class="center"><input name="submit" id="loginSubmit" type="submit" value="Log in" /></p>
</form>
<h2>...or sign up</h2>
<form method="post" action="<?php echo $this->url(array(
    'controller' => 'account',
    'action' => 'signup',
)) ?>">
<p class="right">
<label for="username" accesskey="s">Username:</label>
<input name="username" id="username" type="text" size="20" /><br />
<label for="password">Password:</label>
<input name="password" id="password" type="password" size="20" /><br />
<label for="repeat">Repeat it:</label>
<input name="repeat" id="repeat" type="password" size="20" /><br />
<label for="email" class="info" title="You don't have to enter your e-mail address. But doing so will enable you to reset your password if you ever happen to forget it.">E-mail:</label>
<input name="email" id="email" type="text" size="20" /><br />
<label for="acceptTerms">I accept <a href="<?php echo $this->url(array(
    'controller' => 'about',
    'action' => 'terms',
)); ?>" target="_blank">Taskr Terms of Use</a></label>
<input name="acceptterms" id="acceptTerms" type="checkbox" value="1" />
<script type="text/javascript">
document.write('<input name="tzDiff" id="tzDiff" type="hidden" value="'
    + (new Date().getTimezoneOffset()*-60)
    + '" />');
</script>
</p>
<p class="center"><input name="submit" id="submit" type="submit" value="Sign up" /></p>
</form>
</div> <!-- /wlcSidebar -->
<p>Taskr is a task manager that puts <em>you</em> in control.</p>
<p>Instead of forcing you to assign priorities to your tasks,
and reassign them when things change (remember those "priority 0"
items you've had to do <em>before</em> priority 1 stuff?),
<strong>Taskr relies on your natural ability to focus on what really matters.</strong></p>
<p>It is also a handy task timer, so if you use it you'll soon find
out what you're really spending your time on. And, if you upgrade your
free account to Taskr Pro, then you'll be able to track your time not only
per task, but also per project.</p>

