<div id="login">
<h2>Log in...</h2>
<form method="post" action="">
<p>
<label for="loginUsername">Username:</label>
<input name="username" id="loginUsername" type="text" size="20" value="<?php
echo $this->formData['username'] ?>" /><?php
if (isset($this->formErrors['username'])) {
    echo ' <span class="error">' . $this->formErrors['username'] . '</span>';
} ?><br />
<label for="loginPassword">Password:</label>
<input name="password" id="loginPassword" type="password" size="20" value="<?php
echo $this->formData['password'] ?>" /><?php
if (isset($this->formErrors['password'])) {
    echo ' <span class="error">' . $this->formErrors['password'] . '</span>';
} ?><br />
<label for="rememberme">Remember me:</label>
<input name="rememberme" id="rememberme" type="checkbox" value="1"<?php
if (isset($this->formData['rememberme'])) {
    echo ' checked';
} ?> />
</p>
<p>
<label></label>
<input name="submit" id="loginSubmit" type="submit" value="Log in" /><?php
if (isset($this->formErrors['credentials'])) {
    echo ' <span class="error">' . $this->formErrors['credentials'] . '</span>';
} ?></p>
</form>
<?php if (isset($this->formErrors['credentials'])): ?>
<h2>Forgot password?</h2>
<form method="post" action="<?php echo $this->url(array(
    'controller' => 'account',
    'action' => 'reset-password',
)); ?>">
<p>If you have provided your e-mail address, then you try to reset your password.
Otherwise, you're pretty much out of luck.</p>
<p>
<label for="email">E-mail:</label>
<input name="email" id="email" type="text" size="20" />
</p>
<p>
<label></label>
<input name="submit" type="submit" value="Continue" /></p>
</form>
<?php endif; ?>
</div> <!-- /login -->
