<?php if ($this->formErrors['key']) {
    echo $this->formErrors['key'];
    return;
} ?>
<div id="reset">
<h2>Reset password</h2>
<form method="post" action="">
<p>To complete the password reset, choose a new password and enter it below.
<input name="username" id="username" type="hidden" value="<?php
echo $this->formData['username'] ?>" />
<input name="uid" id="uid" type="hidden" value="<?php
echo $this->formData['uid'] ?>" />
<input name="key" id="key" type="hidden" value="<?php
echo $this->formData['key'] ?>" /></p>
<label for="password">Password:</label>
<input name="password" id="password" type="password" size="20" value="<?php
echo $this->formData['password'] ?>" /><?php
if (isset($this->formErrors['password'])) {
    echo ' <span class="error">' . $this->formErrors['password'] . '</span>';
} ?><br />
<label for="repeat">Repeat password:</label>
<input name="repeat" id="repeat" type="password" size="20" value="<?php
echo $this->formData['repeat'] ?>" /><?php
if (isset($this->formErrors['repeat'])) {
    echo ' <span class="error">' . $this->formErrors['repeat'] . '</span>';
} ?></p>
<p><label></label>
<input name="submit" id="submit" type="submit" value="Save new password" /></p>
</form>
</div> <!-- /reset -->
