<div id="editor">
<form action="" method="post">
<p>Editing: <b><?php echo $this->task->title; ?></b><span id="timer"></span></p>
<p><textarea name="scrap" id="scrap" rows="20" cols="60" accesskey="e"><?php
echo $this->task->scrap; ?></textarea><br />
<label for="liveline" class="info" title="The date before which there's no sense in working on this task">Liveline:</label>
<input type="text" name="liveline" id="liveline" value="<?php
if (isset($this->formData['liveline'])) {
    echo $this->formData['liveline'];
} else {
    echo date($this->showDate($this->task->liveline));
} ?>" />
<label for="deadline" class="info" title="The date when this task has to be finished">Deadline:</label>
<input type="text" name="deadline" id="deadline" accesskey="d" value="<?php
if (isset($this->formData['deadline'])) {
    echo $this->formData['deadline'];
} else {
    echo date($this->showDate($this->task->deadline));
} ?>" />
<label for="finish" class="info" title="Finished tasks can no longer be activated or edited">Finish?</label>
<input type="checkbox" name="finish" id="finish" value="1" accesskey="f" /></p>
<?php if (isset($this->formErrors)) {
    echo "<ul class=\"error\">\n";
    if (isset($this->formErrors['liveline'])) {
        echo '<li> Liveline: ' . $this->formErrors['liveline'] . "</li>\n";
    }
    if (isset($this->formErrors['deadline'])) {
        echo '<li> Deadline: ' . $this->formErrors['deadline'] . "</li>\n";
    }
    echo "</ul>\n";
} ?>
<p class="center">
<input name="submit" type="submit" value="save" accesskey="s" />
<input name="submit" type="submit" value="cancel" accesskey="c" />
</p>
</form>
</div> <!-- /editor -->
