<div id="tasklist">

<?php if ($activeTask = $this->user->getActiveTask()) : ?>
<div id="active">
<form method="post" action="<?php echo $this->url(
    array(
        'controller'    => 'task',
        'action'        => 'edit',
    )); ?>"><div>
<span class="actions">
<input type="submit" name="submit" value="edit" accesskey="e" />
<input type="submit" name="submit" value="stop" accesskey="p" />
</span>
<b>Working on:</b> <?php
echo $activeTask->title;
if ($activeTask->project) {
    echo " <span class=\"details\">(#{$activeTask->project->title})</span>";
}
?><span id="timer" class="details"></span>
<?php if ($activeTask->scrap) { echo $this->showScrap($activeTask->scrap); } ?>
</div></form>
</div> <!-- /active -->
<?php endif; ?>

<div id="new">
<b>New task:</b>
<form method="post" action="<?php echo $this->url(
    array(
        'controller'    => 'task',
        'action'        => 'add',
    )); ?>"><div>
<textarea rows="3" cols="60" name="task-text" accesskey="n"></textarea>
<span class="actions">
<input type="submit" name="add" value="add" accesskey="a" />
</span>
</div></form>
</div> <!-- /new -->

<?php if ($upcomingTasks = $this->user->getUpcomingTasks()) : ?>
<?php $activeProject = $this->user->getActiveProject(); ?>
<div id="upcoming">
<b>To do:</b>
<ul class="tasklist">
<?php $tabindex = 1; foreach($upcomingTasks as $task) : ?>
    <li><a href="<?php echo $this->url(
    array(
        'controller'    => 'task',
        'action'        => 'start',
        'id'            => $task->id,
    )); ?>" tabindex="<?php echo $tabindex++; ?>"><span class="task<?php
if ($task->liveline && $task->liveline > time()) {
    echo ' future';
} elseif ($task->deadline) {
    if ($task->deadline < time()-86400) {
        echo ' overdue';
    } elseif ($task->deadline < time()) {
        echo ' today';
    }
}
if ($activeProject && $activeProject->id == $task->project->id) {
    echo ' active';
}
?>"><?php echo $task->title; ?><?php
if ($task->liveline || $task->deadline || $task->project) {
    unset($details);
    if ($task->liveline) {
        $details = $this->showDate($task->liveline) . ':';
    }
    if ($task->deadline) {
        if (!$details) {
            $details = ':';
        }
        $details .= $this->showDate($task->deadline);
    }
    if ($task->project) {
        if ($details) {
            $details .= ' ';
        }
        $details .= '#' . $task->project->title;
    }
    echo " <span class=\"details\">($details)</span>";
}
?></span></a></li>
<?php endforeach; ?>
</ul>
</div> <!-- /upcoming -->
<?php endif; ?>

<?php if ($finishedTasks = $this->user->getFinishedTasks()) : ?>
<div id="finished">
<form method="post" action="<?php echo $this->url(
    array(
        'controller'    => 'task',
        'action'        => 'hide',
    )); ?>"><div>
<span class="actions">
<input type="submit" name="submit" value="hide" accesskey="h" />
</span>
<b>Finished:</b>
<ul class="tasklist">
<?php foreach($finishedTasks as $task) : ?>
    <li><span class="task"><?php echo $task->title; ?> <span class="details">(<?php echo $this->showDuration($task->duration); ?>)</span></span></li>
<?php endforeach; ?>
</ul>
</div></form>
</div> <!-- /finished -->
<?php endif; ?>

</div> <!-- /tasklist -->
