<?php if (Zend_Auth::getInstance()->hasIdentity()) {
    $user = Zend_Auth::getInstance()->getIdentity();
    $this->headTitle($user->username, 'PREPEND');
} ?>
<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta()->appendHttpEquiv(
        'Content-Type', 'text/html;charset=utf-8'); ?>

    <?php echo $this->headTitle('Taskr')->setSeparator(' - '); ?>

    <?php echo $this->headLink()->prependStylesheet(
            $this->baseUrl() . '/css/style.css'); ?>

    <?php echo $this->headScript(); ?>

</head>
<body<?php if ($this->onLoad) { echo ' onload="' . $this->onLoad . '"' ; } ?>>
<div id="content">

<div id="header">
<?php if (Zend_Auth::getInstance()->hasIdentity()):
    $user = Zend_Auth::getInstance()->getIdentity(); ?>
    <ul>
        <li><b><?php echo $user->username ; ?></b></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'index',
            'action' => 'index',
        )); ?>">Active</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'archive',
            'action' => 'index',
        )); ?>">Archive</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'account',
            'action' => 'index',
        )); ?>">Account</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'account',
            'action' => 'logout',
        )); ?>">Sign out</a></li>
    </ul>
<?php endif; ?>
    <h1><a href="<?php echo $this->url(array(
        'controller' => 'index',
        'action' => 'index',
    ));; ?>">Taskr</a></h1>
    <p>take your time</p>
</div> <!-- /header -->

<?php echo $this->layout()->content; ?>

<div id="footer">
    <ul>
        <li>&copy; 2010 taskr.eu |</li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'about',
            'action' => 'index',
        ));; ?>">About</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'about',
            'action' => 'terms',
        ));; ?>">Terms</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'about',
            'action' => 'help',
        ));; ?>">Help</a></li>
    </ul>
</div> <!-- /footer -->

</div> <!-- /content -->
</body>
</html>
