<?php /*
    $this->headMeta()->appendHttpEquiv(
        'Content-Type', 'text/html;charset=utf-8'
    );
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('Taskr');
*/ ?>
<?php echo $this->doctype('XHTML1_STRICT'); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headMeta()->appendHttpEquiv(
        'Content-Type', 'text/html;charset=utf-8'); ?>

    <?php echo $this->headTitle('Taskr')->setSeparator(' - '); ?>

    <?php echo $this->headLink()->prependStylesheet(
            $this->baseUrl() . '/css/style.css'); ?>

    <?php echo $this->headScript(); ?>

</head>
<body<?php if ($this->onLoad) { echo ' onload="' . $this->onLoad . '"' ; } ?>>
<div id="content">

<div id="header">
<?php if (isset($this->user)): ?>
    <ul>
        <li><b><?php echo $this->user->username ; ?></b></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'archive',
            'action' => 'index',
        )); ?>">Archive</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'account',
            'action' => 'profile',
        )); ?>">Profile</a></li>
        <li><a href="<?php echo $this->url(array(
            'controller' => 'account',
            'action' => 'logout',
        )); ?>">Sign out</a></li>
    </ul>
<?php endif; ?>
    <h1><a href="<?php echo $this->url(array(
        'controller' => 'index',
        'action' => 'index',
    ));; ?>">Taskr</a></h1>
    <p>take your time</p>
</div> <!-- /header -->

<?php echo $this->layout()->content; ?>

<div id="footer">
    <ul>
        <li>&copy; 2010 taskr.eu</li>
        <li>About</li>
        <li>Contact</li>
        <li>Blog</li>
        <li>Legal</li>
    </ul>
</div> <!-- /footer -->

</div> <!-- /content -->
</body>
</html>
