<h2>About Taskr</h2>

<p>Taskr is a task manager that puts <em>you</em> in control.</p>

<p>Instead of forcing you to assign priorities to your tasks,
and reassign them when things change (remember those "priority 0"
items you've had to do before priority 1 stuff?), <strong>Taskr relies on
your natural ability to focus on what really matters.</strong>

<p>It is also a handy task timer, so if you use it you'll soon find
out what you're really spending your time on. And, if you upgrade your
free account to Taskr Pro*, then you'll be able to track your time not
only per task, but also per project.</p>

<p>* Taskr Pro will be available once we complete the private beta testing.
Until then, invited users will be given Pro permissions shortly after they
sign up.</p>

<h2>About Taskr.eu</h2>

<p>Taskr.eu is a team of two hackers who have found all other task management
tools to be falling rather short of their expectations.</p>

<p style="clear:both"><img src="http://2.bp.blogspot.com/_xNgh16yr_ws/Snd1gxOJ91I/AAAAAAAAAUA/nHefusTXez0/S220/val_03_1kc1.jpg"
style="float:left; margin:0 10px 10px 0" width="100px" /><strong>Villem Alango</strong>
came up with the original idea and built the pre-prototype of Taskr, using
nothing but OpenOffice.org. Now, he's in charge of the MySQL backend
and unit testing.</p>

<p style="clear:both"><img src="http://peeterpaul.motskula.net/img/wolli180.jpg"
style="float:left; margin:0 10px 10px 0" width="100px" /><strong>Peeter P. Mõtsküla</strong>
built most of the PHP code and all of the bugs therein, and created the
initial look-and-feel. Peeter is also responsible for usability, version
control, and licensing.</p>

<p style="clear:both">As soon as we're reasonably satisfied with what we've
created, we'll set up a company, start selling Taskr Pro subscriptions,
hire a secretary and buy an espresso machine.</p>

