<h2>Terms of Use</h2>

<p>Taskr is currently in private beta, so the rules are simple:</p>

<ol>
    <li>You will let us know what you like and what you hate about Taskr.</li>
    <li>We try hard not to crash the database. However, sheet happens.
You have been warned.</li>
    <li>The private beta is over when we say so. After that, you will
probably have to pay us a little for your continued use of Pro privileges. Or
continue as free users.</li>
    <li>We may update these Terms of Use at any time. We will certainly do so
when we decide to end the private beta.</li>
</ol>

<h2>Your privacy</h2>

<ol>
    <li>We will never sell your email address to anyone.</li>
    <li>We do our best to keep our database secure. However, sheet happens.
You have been warned.</li>
    <li>You can delete your account at any time. When you do so, all your data
(tasks, projects, scraps) will be permanently removed.</li>
</ol>
